import { useEffect } from 'react'
import styles from './AiReportModal.module.css'

export default function AiReportModal({ report, onClose }) {
  // Close on Escape key
  useEffect(() => {
    function handleKey(e) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [onClose])

  return (
    <div className={styles.backdrop} onClick={onClose} role="dialog" aria-modal="true" aria-label="AI Incident Report">
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <span className={styles.aiIcon}>🤖</span>
            <h2 className={styles.title}>AI Incident Report</h2>
          </div>
          <button className={styles.close} onClick={onClose} aria-label="Close modal">✕</button>
        </div>
        <div className={styles.body}>
          <pre className={styles.report}>{report}</pre>
        </div>
        <div className={styles.footer}>
          <span className={styles.note}>Generated by Groq LLM · Site Reliability Engineer AI</span>
          <button className={styles.closeBtn} onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  )
}
